// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3668.Stronghold.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc3668.Stronghold.Settings;

/**
 *
 */
public class CMDautoLowBar extends CommandGroup {

	public CMDautoLowBar() {

		// Add Commands here:
		// e.g. addSequential(new Command1());
		// addSequential(new Command2());
		// these will run in order.

		// To run multiple commands at the same time,
		// use addParallel()
		// e.g. addParallel(new Command1());
		// addSequential(new Command2());
		// Command1 and Command2 will run in parallel.

		// A command group will require all of the subsystems that each member
		// would require.
		// e.g. if Command1 requires chassis, and Command2 requires arm,
		// a CommandGroup containing them would require both the chassis and the
		// arm.
		addSequential(new CMDdrive(Settings.Auto_InchesFromOuterworksLowBar, 0, Settings.Auto_DriveSpeed));
		//addSequential(new CMDdriveDelay(Settings.Auto_delayTimeMillis));
		addSequential(new CMDdrive(Settings.Auto_LowbarDriveForward2, Settings.Auto_LowbarAngleHeading1, Settings.Auto_DriveSpeed));
		addSequential(new CMDturn(Settings.Auto_TurnHeadingLowBar));
		//addSequential(new CMDdriveDelay(Settings.Auto_delayTimeMillis));
		addSequential(new CMDdrive(Settings.Auto_InchesToTowerLowBar, Settings.Auto_TurnHeadingLowBar, Settings.Auto_DriveSpeed));
		addSequential(new CMDautoRoller(Settings.Auto_RunRollerMotorSeconds));

	}
}
