// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3668.Stronghold.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3668.Stronghold.Robot;
import edu.wpi.first.wpilibj.AnalogGyro;
/**
 *
 */
public class CMDdriveForward extends Command {
	boolean _isFinished;
	int _Distance;
	double _Kp = 0.03;
	double _gyroAngle;
	double _initialHeading;
	

    public CMDdriveForward(int Distance) {
    	_Distance = Distance;
   
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.chassis.resetEncoder();
    	_isFinished = false;
    	System.out.println("CMDdriveForward");
    	_initialHeading = Robot.chassis.getGyroAngle();
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (Robot.chassis.getEncoderValue() < _Distance){
    		_gyroAngle = Robot.chassis.getGyroAngle();
    		//Robot.chassis.drive(.5, -(_gyroAngle - _initialHeading)*_Kp);
    		Robot.chassis.drive(.5, 0);
    		_isFinished = false;
    	}
    	else {
    		Robot.chassis.drive(0, 0);
    		_isFinished = true;
    	}
    	//System.out.println(Robot.chassis.getEncoderValue());
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return _isFinished;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.chassis.drive(0, 0);
    }
}
